server:
  port: 83
spring:
  application:
    name: nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#消费者将要去访问微服务的名称(已经注册进入nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider